import json
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\adamj\Desktop\_KANCELARIA\OBSIL")
TASK_DIR = ROOT / "baza_wiedzy" / "kolejka_79" / "zadania" / "OBS-057" / "80efa5b5c5d64bb2b3709a3fe839d8e1"
job = json.loads((TASK_DIR / "zlecenie.json").read_text(encoding="utf-8"))
sources = {
    source["id"]: (ROOT / source["text"]).read_text(encoding="utf-8-sig").splitlines()
    for source in job["sources"]
}

def quote(source_id, start, end):
    return "\n".join(sources[source_id][start - 1:end])

result = {
    "task_id": "80efa5b5c5d64bb2b3709a3fe839d8e1",
    "concept_id": "OBS-057",
    "label": "sprzeczność interesów w materialnym sensie",
    "points": ["S1-K1-04", "S1-K1-06", "S2-K3-05", "S2-K3-08", "S2-K4-03", "S2-K4-06"],
    "scope": "Uzupełniam odrębne od SP-R04 znaczenie materialnej sprzeczności interesów: definicję i granicę między interesem prawnym/procesowym a pozaprawnym, a także zakres interpretacji dotyczącej art. 30 ust. 1. Nie powielam testu sprawy tożsamej lub związanej i odrębnej oceny sprzeczności z SP-R04, rozróżnienia zakazu z art. 28 ust. 2 w SP-R05, art. 28 ust. 3 w SP-R06 ani doradztwa w SP-R07. Dla art. 28 ust. 2 komentarz opisuje odrębny formalny standard, bez indywidualnej oceny sprzeczności; nie przenoszę go na art. 28 ust. 1, ust. 3 ani doradztwo jako gotowej reguły. OBS-030-R02 i OBS-030-Q01 obejmują katalog przykładów i próg rozbieżność/sprzeczność w kontekście obrony kilku oskarżonych, dlatego nie tworzę ponownego pytania o ten próg. Art. 30 ust. 1 i znaczne ryzyko ujmuję osobno od rzeczywistej sprzeczności. SRC-01 i SRC-03 przedstawiają poglądy tego samego autora, nie są niezależnymi opiniami. Zakres jest częściowy: dostępne fragmenty nie ustanawiają miary oceny pozaprawnego interesu ani ekspercko potwierdzonej wykładni art. 30.",
    "completeness": "partial",
    "operator_status": "OCZEKUJE",
    "existing_record_refs": ["SP-R04", "SP-R05", "SP-R06", "SP-R07", "SP-R08", "OBS-030-R02", "OBS-076-R06"],
    "coverage": [
        {"source_id": "SRC-01", "status": "CZESCIOWY", "read_ranges": "928; 964-976; 1276", "notes": "Komentarz P. Skuczyńskiego: definicja sprzeczności przy art. 28 ust. 1, odrębny standard art. 28 ust. 2 i pogląd o interpretacji art. 30 ust. 1 przez pryzmat wcześniejszego sformułowania. Cytowane zmiany są w wersji do korekty; w. 1276 formułuje tę interpretację ostrożnie."},
        {"source_id": "SRC-02", "status": "CZESCIOWY", "read_ranges": "18-32; 70-76", "notes": "Wybrane relacje o WO-134/19, WO-31/24, WO-82/24, WO-226/24, WO-164/22 i WO-173/22. Pokazują konkretne konfiguracje konfliktowe, ale nie formułują ogólnej definicji materialnej sprzeczności. To wtórny wybór, nie pełne uzasadnienia."},
        {"source_id": "SRC-03", "status": "CZESCIOWY", "read_ranges": "348-365; 625-656; 723-730", "notes": "Poradnik omawia lojalność, rozróżnienie konfliktu materialnego i formalnego oraz art. 30 i znaczne ryzyko. W. 647 zawiera dosłowny marker redakcyjny „???”, zachowany w cytacie; Astra wzrokowo potwierdziła jego obecność i kolorowe wyróżnienie na oryginalnej stronie 17 PDF. To ten sam autor co SRC-01, nie niezależne potwierdzenie."},
        {"source_id": "SRC-04", "status": "CZESCIOWY", "read_ranges": "187-211", "notes": "Odczytano art. 28-30: tekst rozdziela sprzeczność interesów w art. 28 ust. 1 i 3 oraz art. 29 od konfliktu lub znacznego ryzyka w art. 30. Tekst przepisu nie definiuje tu testu materialnego."},
        {"source_id": "SRC-05", "status": "CZESCIOWY", "read_ranges": "47; 93-123", "notes": "Sprawdzono przepisy ustawy o radcach prawnych dotyczące pomocy prawnej i wykonywania zawodu jako kontekst. Nie zawierają odrębnej definicji sprzeczności interesów dla wskazanych punktów."},
        {"source_id": "SRC-06", "status": "CZESCIOWY", "read_ranges": "79-137", "notes": "Wtórne zestawienie lokalnych przepisów dotyczących konfiguracji konfliktowych, w tym art. 28-30. Nie jest niezależnym źródłem wykładni ani definicji."},
        {"source_id": "SRC-07", "status": "CZESCIOWY", "read_ranges": "139-171", "notes": "Wybrane streszczenia i cytaty z WO-17/24, WO-25/24, WO-42/24, WO-89/21 i WO-122/23. Ilustrują konkretne relacje interesów; nie ustanawiają ogólnej definicji. Brak pełnych oryginałów w tym pliku."},
        {"source_id": "SRC-08", "status": "SPRAWDZONY", "read_ranges": "1-35", "notes": "Cały plik dotyczy sprawy tej samej lub związanej; nie definiuje materialnej sprzeczności interesów."},
        {"source_id": "SRC-09", "status": "SPRAWDZONY", "read_ranges": "1-37", "notes": "Cały plik dotyczy klienta aktualnego i byłego; nie definiuje materialnej sprzeczności interesów."}
    ],
    "meanings": [
        {"id": "OBS-057-M01", "context": "Wspólny rdzeń pojęcia dla art. 28 ust. 1 i 3, art. 29 ust. 1 pkt 1 i 2 oraz punktów S1-K1-04/06", "description": "W komentarzu materialna sprzeczność oznacza niemożność jednoczesnej realizacji interesów, gdy realizacja jednego odbywa się kosztem drugiego. Interes należy ujmować przede wszystkim prawnie lub procesowo, ale autor dopuszcza również interes pozaprawny, na przykład ekonomiczny; gdy jego treści nie wyznaczają przepisy i sytuacja prawna, odsyła do rozumienia klienta. Poradnik odróżnia tę ocenę od formalnego stwierdzenia określonego układu podmiotowego. Art. 28 ust. 2 opisuje jako wyjątek od wymogu odrębnej oceny, nie zaś jako definicję sprzeczności dla innych punktów.", "record_ids": ["OBS-057-R01", "OBS-057-R02", "SP-R04", "SP-R05", "SP-R06", "SP-R07"]},
        {"id": "OBS-057-M02", "context": "Art. 30 ust. 1, konflikt między klientem a radcą lub osobą najbliższą, punkty S1-K1-04/06", "description": "Komentarz interpretuje konflikt z art. 30 ust. 1 jako ocenę zbliżoną do materialnej sprzeczności: realizacja interesu radcy lub osoby najbliższej nie może następować bez uszczerbku dla klienta i odwrotnie. Autor odrębnie obejmuje rzeczywisty konflikt oraz jego potencjalne wystąpienie oceniane przez radcę jako znaczne ryzyko. Jest to pogląd autora, nie dodatkowy tekst normatywny ani przyjęta wykładnia ekspercka.", "record_ids": ["OBS-057-R03", "SP-R08"]},
        {"id": "OBS-057-M03", "context": "Zastosowanie pojęcia przy reprezentacji i doradztwie dla aktualnych oraz byłych klientów, punkty S2-K3-05/08 i S2-K4-03/06", "description": "Pojęcie materialnej sprzeczności jest jedną z odrębnych przesłanek zależnych od właściwej konfiguracji i rodzaju czynności. Wspólna definicja nie usuwa pozostałych wymagań: art. 28 ust. 1 i 3 odnoszą się do reprezentacji w tej samej lub związanej sprawie, art. 29 do doradztwa; art. 28 ust. 2 w komentarzu nie wymaga osobnej oceny sprzeczności. Sugestia autora, by blokadę z art. 28 ust. 2 przenieść na doradztwo, pozostaje osobnym poglądem zapisanym w OBS-076-R06, nie wynika z samej definicji materialnej.", "record_ids": ["OBS-057-R01", "SP-R04", "SP-R05", "SP-R06", "SP-R07", "OBS-076-R06"]}
    ],
    "records": [
        {"id": "OBS-057-R01", "kind": "poglad_autora", "claim": "Autor komentarza definiuje materialną sprzeczność interesów jako niemożność jednoczesnego realizowania dwóch lub więcej interesów, gdy osiągnięcie jednego odbywa się kosztem drugiego. Interes ujmuje przede wszystkim jako prawnie chroniony lub procesowy, ale dopuszcza także kategorię pozaprawną, na przykład ekonomiczną; w jej nieokreślonych prawnie aspektach odsyła do rozumienia klienta.", "speaker": "P. Skuczyński, autor komentarza SRC-01", "role": "autor komentarza roboczego do korekty autorskiej", "context": "Omówienie ogólnego standardu art. 28 ust. 1 dla aktualnych klientów będących obrońcami lub pełnomocnikami. Autor wyjaśnia, że ustalenie sprzeczności jest odrębne od ustalenia tożsamości lub związku spraw.", "court_treatment": "nie_dotyczy; pogląd autora komentarza, nie teza sądu ani przepis", "source_status": "komentarz roboczy w wersji do korekty; zdanie definicyjne w wykorzystanym wierszu nie jest oznaczone jako skreślenie ani wstawka", "evidence": [{"source_id": "SRC-01", "line_start": 928, "line_end": 928, "quote": quote("SRC-01", 928, 928)}], "limits": "Definicja jest ogólna i nie wskazuje mierników ważenia, stopnia uszczerbku ani przykładów dla interesu pozaprawnego. Autor wskazuje rozumienie klienta jako punkt odniesienia, gdy jego treści nie wyznaczają przepisy i sytuacja prawna. Nie rozciąga się jej na każdy formalny zakaz konfliktu, zwłaszcza art. 28 ust. 2 opisany w SP-R05."},
        {"id": "OBS-057-R02", "kind": "poglad_autora", "claim": "Autor poradnika odróżnia konflikt materialny, wymagający oceny sprzeczności interesów, od konfliktu formalnego, przy którym wystarczy ustalenie okoliczności wskazanej w danym przepisie. Materialną sprzeczność opisuje jako zobowiązanie radcy do działania na rzecz określonych podmiotów, gdy realizacja interesu jednego uszczupla interes drugiego. Wskazuje, że ocena ma zastosowanie do wymienionych przez niego przesłanek art. 28 ust. 1 i 3, art. 29 ust. 1 pkt 1 i 2 oraz art. 30 ust. 1; odrębnie zalicza art. 27 i art. 28 ust. 2 do układów bez wymogu takiej oceny.", "speaker": "P. Skuczyński, autor poradnika SRC-03", "role": "autor opracowania poradnikowego", "context": "Rozdział o badaniu konfliktu interesów. W. 647 zawiera nierozstrzygnięty marker redakcyjny ??? w zdaniu wyliczającym przepisy.", "court_treatment": "nie_dotyczy; pogląd autora poradnika, nie stanowisko sądu", "source_status": "tekst poradnika z markerem redakcyjnym w wyliczeniu przepisów; w. 647 nie poprawiono ani nie odtworzono domyślnie", "evidence": [{"source_id": "SRC-03", "line_start": 641, "line_end": 656, "quote": quote("SRC-03", 641, 656)}], "limits": "Lista w w. 647 zawiera marker ???, dlatego jej brzmienia redakcyjnego nie traktuję jako pewnego. Lokalny tekst KERP potwierdza brzmienie art. 28-30, ale nie usuwa niepewności co do statusu fragmentu poradnika. Art. 28 ust. 2 i art. 27 pozostają odrębnymi kategoriami w ujęciu autora. SRC-01 i SRC-03 są tego samego autora, więc zbieżność nie stanowi niezależnego potwierdzenia."},
        {"id": "OBS-057-R03", "kind": "poglad_autora", "claim": "Autor poradnika odczytuje konflikt z art. 30 ust. 1 jako ocenę zbliżoną do sprzeczności materialnej między interesem klienta a interesem radcy lub osoby mu najbliższej. Obejmuje to zarówno konflikt rzeczywisty, jak i możliwość jego powstania, gdy radca ocenia ryzyko jako znaczne. W komentarzu do art. 30 autor dodaje, że wcześniejsze brzmienie przepisu mówiło o sprzeczności interesów i że wydaje się właściwe zachowanie tej interpretacji; zaznacza również wymóg indywidualnej oceny.", "speaker": "P. Skuczyński, autor komentarza SRC-01 i poradnika SRC-03", "role": "autor dwóch lokalnych opracowań, nie niezależny ekspert ani sąd", "context": "Konfiguracja interesu klienta przeciwstawionego interesowi własnemu radcy lub osoby mu najbliższej, art. 30 ust. 1. Ujęcie obejmuje ocenę potencjalnego konfliktu o odrębnym znaczniku znacznego ryzyka.", "court_treatment": "nie_dotyczy; wyłącznie wykładnia autora", "source_status": "SRC-03 formułuje analogię stanowczo, SRC-01 wskazuje ją ostrożniej przez „wydaje się”; oba teksty są tego samego autora, więc różnica tonu nie dowodzi dwóch poglądów ani niezależnego potwierdzenia", "evidence": [{"source_id": "SRC-03", "line_start": 723, "line_end": 730, "quote": quote("SRC-03", 723, 730)}, {"source_id": "SRC-01", "line_start": 1276, "line_end": 1276, "quote": quote("SRC-01", 1276, 1276)}], "limits": "Lokalny art. 30 ust. 1 odrębnie wymienia konflikt interesów i znaczne ryzyko jego wystąpienia. Autor nie podaje liczbowego ani faktograficznego progu „znacznego” ryzyka. Jego analogia do materialnej sprzeczności jest poglądem komentatorskim; nie utożsamiam potencjalnego ryzyka z już stwierdzoną sprzecznością ani nie przedstawiam tej interpretacji jako rozstrzygniętej."}
    ],
    "relations": [],
    "gaps": [
        {"id": "OBS-057-G01", "issue": "Definicja opisuje relację między interesami, lecz nie podaje sposobu oceny ich wagi ani stopnia uszczerbku. W przypadku interesu pozaprawnego odsyła do rozumienia klienta, ale nie wyjaśnia, jak ustalać to rozumienie ani jak rozwiązać jego niejednoznaczność.", "needed": "Przykłady graniczne i wskazanie kryteriów stosowania testu do interesów pozaprawnych, bez zastępowania oceny klienta założeniem o interesie typowym."},
        {"id": "OBS-057-G02", "issue": "Marker ??? z poradnika SRC-03 w. 647 jest obecny i wyróżniony kolorem także na oryginalnej stronie 17 PDF, co potwierdziła Astra wzrokowo. Sam materiał nie wyjaśnia, czy marker jest uwagą autora, czy żądaniem redakcyjnym, ani jak należy domknąć zdanie.", "needed": "Wyjaśnienie intencji autora lub redakcji poradnika; do tego czasu zachować marker i nie traktować wyliczenia z w. 647 jako pewnej finalnej redakcji."},
        {"id": "OBS-057-G03", "issue": "Kryterium art. 30 ust. 1 i znaczenie „znacznego ryzyka” są tu przedstawione wyłącznie jako interpretacja jednego autora. Przytoczone materiały nie zawierają niezależnego eksperckiego potwierdzenia ani konkretnego testu poziomu ryzyka.", "needed": "Ekspercka ocena, czy w aktualnym brzmieniu art. 30 ust. 1 konflikt należy utożsamiać z materialną sprzecznością oraz jaki odrębny próg stosować dla znacznego ryzyka."}
    ],
    "questions": [
        {"id": "OBS-057-Q01", "record_ids": ["OBS-057-R03", "SP-R08"], "understanding": "Tekst art. 30 ust. 1 mówi o konflikcie interesów lub znacznym ryzyku jego wystąpienia. Autor SRC-03 objaśnia konflikt przez ocenę zbliżoną do materialnej sprzeczności, a ryzyko jako jej możliwe przyszłe wystąpienie oceniane przez radcę; autor SRC-01 ostrożnie odwołuje się do wcześniejszego brzmienia o sprzeczności. To jedno stanowisko autora w dwóch opracowaniach, nie dwa niezależne potwierdzenia.", "variants": "A: materialny test niemożności realizacji jednego interesu bez uszczerbku dla drugiego jest zasadniczą treścią „konfliktu” z art. 30 ust. 1, a „znaczne ryzyko” oznacza znaczące prawdopodobieństwo wystąpienia takiego konfliktu. B: materialny test jest jedynie analogią pomocniczą, a obecny zwrot „konflikt interesów” wymaga autonomicznej oceny; znaczne ryzyko stanowi odrębną alternatywną przesłankę. C: test materialny stosuje się do konfliktu rzeczywistego, lecz poziom „znacznego ryzyka” wymaga osobnego kryterium, którego autor nie określa.", "consequences": "Odpowiedź wyznaczy, czy ocena art. 30 może używać tego samego materialnego testu co art. 28 ust. 1 i art. 29, oraz jak osobno dokumentować konflikt istniejący i jego znaczne ryzyko. Nie zmieni odrębnych przesłanek związku sprawy ani nie uczyni analogii autora rozstrzygniętą normą.", "question": "Czy konflikt z art. 30 ust. 1 należy rozumieć przez materialny test niemożności realizacji jednego interesu bez uszczerbku dla drugiego, czy jako odrębną kategorię, dla której test ten ma tylko znaczenie pomocnicze? Jak wyznaczać „znaczne ryzyko” jego wystąpienia i odróżniać tę przesłankę od konfliktu już istniejącego?", "needed": "Wykładnia ekspercka aktualnego art. 30 ust. 1, w szczególności relacji między konfliktem istniejącym, materialną sprzecznością i alternatywną przesłanką znacznego ryzyka."}
    ],
    "self_check": "Sprawdzono relewantne fragmenty wszystkich dziewięciu źródeł; zakresy i ograniczenia podano osobno, bez deklarowania pełnej lektury dużych plików. Cytaty OBS-057-R01-R03 pobiera skrypt z dokładnych ciągłych wierszy manifestu bez normalizacji; marker redakcyjny ??? zachowano. Astra wzrokowo sprawdziła oryginalną stronę 17 PDF SRC-03 i potwierdziła obecność markera. SRC-01 i SRC-03 mają tego samego autora, nie policzono ich jako niezależnego potwierdzenia. Rozdzielono pogląd autora, tekst KERP, zakres art. 28 ust. 2 i pytanie eksperckie o art. 30. OBS-030-Q01 pozostaje ograniczone do progu przy obronie kilku oskarżonych i nie zostało powielone. Operator status OCZEKUJE; odbiór pozostaje po stronie Astry."
}

out = TASK_DIR / "wynik.json"
out.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(out)

sys.path.insert(0, str(ROOT / "narzedzia" / "kolejka_pojec"))
import kolejka
state = kolejka.load(ROOT / "baza_wiedzy" / "kolejka_79")
task = kolejka.get_job(state, result["concept_id"])
kolejka.validate_result(state, task, result)
print("validate_result: OK (bez zapisu do kolejki)")
