import json
from pathlib import Path

HERE = Path(__file__).parent
PROJECT = Path(r"C:\Users\adamj\Desktop\_KANCELARIA\OBSIL")
task = json.loads((HERE / "zlecenie.json").read_text(encoding="utf-8-sig"))
src = {s["id"]: (PROJECT / s["text"]).read_text(encoding="utf-8-sig").splitlines() for s in task["sources"]}

def evidence(sid, start, end):
    return {"source_id": sid, "line_start": start, "line_end": end, "quote": "\n".join(src[sid][start-1:end])}

result = {
  "task_id": task["task_id"], "concept_id": task["concept_id"], "label": task["label"], "points": task["points"],
  "scope": "Uzupełnienie o rozdział norm dla reprezentacji i doradztwa przy wcześniejszej obsłudze oraz o odrębny zakres tajemnicy zawodowej. Nie powtarza KL-R04/07/08/09/10 ani OBS-002-R03–R07. Wspólny temat chwili zakończenia relacji i utrzymanego pełnomocnictwa jest już ujęty w OBS-002-Q01 i KL-G02; nie formułuję drugiego pytania o te zdarzenia. Historyczne KL-R09/R10 pozostają odniesieniem, nie są przepisywane.",
  "completeness": "partial", "operator_status": "OCZEKUJE", "existing_record_refs": ["KL-R09", "KL-R10"],
  "coverage": [
    {"source_id":"SRC-01","status":"CZESCIOWY","read_ranges":"972-992; 1064-1084","notes":"Komentarz redakcyjny do korekty; blok 972-992 przeczytany z otoczeniem. D 106/18 sprawdzono dla oddzielenia zagadnienia wspólnego z OBS-002, bez ponawiania jego rekordu."},
    {"source_id":"SRC-02","status":"CZESCIOWY","read_ranges":"28-32; 70-76","notes":"Wybór orzeczeń, przejrzane fragmenty dla rozróżnienia zakresu wcześniejszej obsługi; bez powtarzania OBS-002-R05/R06 i KL-R07."},
    {"source_id":"SRC-03","status":"CZESCIOWY","read_ranges":"300-340; 368-392","notes":"Opracowanie autora o tajemnicy i rejestrze; fragment 312-329 pokrywa się z KL-R09, a 374-392 z KL-R10, więc nie tworzę powtórzeń."},
    {"source_id":"SRC-04","status":"CZESCIOWY","read_ranges":"113-121; 187-203","notes":"Tekst lokalnej kopii KERP: zakres i czas tajemnicy, rozdział art. 28 ust. 3 i art. 29 ust. 1 pkt 2."},
    {"source_id":"SRC-05","status":"CZESCIOWY","read_ranges":"75-100","notes":"Sprawdzono przepisy ustawy w otoczeniu art. 6 oraz terminów przechowywania danych; nie znaleziono w tym zakresie niezależnego doprecyzowania pojęcia byłego klienta."},
    {"source_id":"SRC-06","status":"CZESCIOWY","read_ranges":"117-147; 292-310","notes":"Wtórna mapa przepisów rozróżnia reprezentację i doradztwo dla aktualnego oraz uprzednio obsługiwanego podmiotu; porównana z lokalnym tekstem KERP, nie traktowana jako norma."},
    {"source_id":"SRC-07","status":"CZESCIOWY","read_ranges":"101-105; 143-147","notes":"Wtórne opisy WO–82/20 i WO–25/24; odnoszą się do ochrony po obsłudze, lecz nie wnoszą odrębnego kryterium ponad kartę historyczną i OBS-002."},
    {"source_id":"SRC-08","status":"SPRAWDZONY","read_ranges":"1-35","notes":"Cała krótka karta o związku spraw; dotyczy osi sprawy, nie nowego kryterium byłego klienta."},
    {"source_id":"SRC-09","status":"SPRAWDZONY","read_ranges":"1-37","notes":"Cała krótka karta klienta aktualnego/byłego; skonfrontowana z KERP i kartą historyczną. Nie powielam jej twierdzeń ani wskazówek."}
  ],
  "meanings": [
    {"id":"OBS-007-M01","context":"Uprzednia obsługa a rodzaj obecnej czynności","description":"W KERP ścieżka dla aktualnej reprezentacji lub obrony przy wcześniejszych czynnościach wynika z art. 28 ust. 3, a dla aktualnego doradztwa wobec osoby wcześniej obsługiwanej z art. 29 ust. 1 pkt 2. Komentarz SRC-01 w tej drugiej konfiguracji wskazuje pkt 1, co jest sprzeczne z lokalnym tekstem KERP i wymaga wyjaśnienia, zamiast automatycznej korekty źródła.","record_ids":["OBS-007-R01"]},
    {"id":"OBS-007-M02","context":"Tajemnica zawodowa po zakończeniu pomocy","description":"Zakres informacji objętych tajemnicą i czas obowiązku jej zachowania tworzą odrębną oś od oznaczenia osoby jako aktualnego lub byłego klienta. Trwanie tajemnicy nie przesądza samo przez się o trwaniu relacji klienta.","record_ids":["OBS-007-R02"]}
  ],
  "records": [
    {"id":"OBS-007-R01","kind":"NORMA","claim":"Lokalny tekst KERP wiąże wcześniejsze czynności zawodowe z art. 28 ust. 3 w przypadku obecnej reprezentacji lub obrony, a przy obecnym doradztwie z art. 29 ust. 1 pkt 2. Komentarz redakcyjny SRC-01, omawiając konflikt aktualnego i byłego klienta przy doradztwie, odsyła do art. 29 ust. 1 pkt 1. Jest to rozbieżność między komentarzem a przytoczonym tekstem KERP.","speaker":"KERP, art. 28 ust. 3 i art. 29 ust. 1 pkt 2; P. Skuczyński, komentarz SRC-01","role":"norma lokalna oraz odrębnie pogląd autora komentarza do korekty","context":"Odróżnienie obecnej reprezentacji/obrony od obecnego doradztwa, gdy druga osoba była wcześniej obsługiwana.","court_treatment":"Nie dotyczy. Nie wyprowadzono wykładni sądu ani nie skorygowano komentarza w miejsce autora.","source_status":"tekst KERP w lokalnym korpusie oraz komentarz redakcyjny w wersji do korekty","evidence":[evidence("SRC-04",187,201),evidence("SRC-01",984,988)],"limits":"Nie powtarza tezy KL-R08 o tym, że wcześniejsze czynności obejmują różne formy pomocy. Stwierdza jedynie rozdział podstaw normatywnych i rozbieżność numeru punktu. Nie przesądza wyjątków zgody z art. 29 ust. 2, opisanych w odrębnym haśle OBS-076."},
    {"id":"OBS-007-R02","kind":"NORMA","claim":"Art. 15 KERP określa tajemnicę przez informacje dotyczące klienta i jego spraw związane z czynnościami zawodowymi, w tym warunkowo informacje ujawnione przed podjęciem czynności. Art. 17 stanowi, że obowiązku nie można ograniczyć w czasie i że trwa po zaprzestaniu wykonywania zawodu. To zakres ochrony informacji, a nie samodzielny test aktualnego lub byłego statusu klienta.","speaker":"KERP, art. 15 ust. 1-3 i art. 17","role":"norma etyki zawodowej w lokalnej kopii","context":"Odrębność tajemnicy zawodowej od przesłanek konfliktu opartych na aktualnej lub uprzedniej obsłudze.","court_treatment":"Nie dotyczy.","source_status":"tekst KERP w lokalnym korpusie","evidence":[evidence("SRC-04",113,121)],"limits":"Nie określa daty ustania relacji klienta ani nie zastępuje oceny przesłanek art. 28-29. Zakres tajemnicy dla danych sprzed czynności zależy od przesłanki z art. 15 ust. 3."}
  ],
  "relations": [],
  "gaps": [
    {"id":"OBS-007-G01","issue":"Komentarz SRC-01 w omówieniu uprzednio obsłużonej osoby wskazuje art. 29 ust. 1 pkt 1, podczas gdy lokalny tekst KERP w art. 29 ust. 1 pkt 2 mówi o osobie, na rzecz której radca uprzednio wykonywał czynności zawodowe. Nie wiadomo, czy numer w komentarzu jest omyłką redakcyjną, czy odzwierciedla szerszy problem wykładni.","needed":"Wyjaśnienie autora lub kontrola finalnej wersji komentarza. Nie poprawiać cytowanego komentarza ani nie przedstawiać go jako zgodnego z tekstem normy bez oznaczenia rozbieżności."}
  ],
  "questions": [
    {"id":"OBS-007-Q01","record_ids":["OBS-007-R01"],"understanding":"Przepis rozróżnia obecne bycie obrońcą lub pełnomocnikiem od obecnego doradztwa; w drugim przypadku właściwą wzmianką o uprzedniej obsłudze wydaje się art. 29 ust. 1 pkt 2. Komentarz SRC-01 odsyła do pkt 1.","variants":"Wariant A: odesłanie w SRC-01 do pkt 1 jest omyłką i chodzi o pkt 2; wariant B: autor zamierzał szerszą konstrukcję, której nie da się odtworzyć z lokalnego tekstu przepisu; wariant C: pozostawić mapowanie jako nierozstrzygniętą rozbieżność do czasu wyjaśnienia.","consequences":"Przy wariancie A OBSIL może osobno wiązać rodzaj aktualnej czynności i rodzaj wcześniejszej obsługi z odpowiednią normą. Wariant B wymaga zapisania wykładni autora i jej granic. Wariant C zapobiega utrwaleniu błędnego odesłania w automatycznym mapowaniu.","question":"Czy odesłanie autora komentarza do art. 29 ust. 1 pkt 1 w omówieniu aktualnego doradztwa wobec uprzednio obsługiwanej osoby należy traktować jako omyłkę na rzecz pkt 2? Czy dla porządkowania konfliktów należy osobno oznaczać rodzaj obecnej czynności i rodzaj czynności uprzedniej?","needed":"Wyjaśnienie eksperta lub autora komentarza; pytanie nie dotyczy chwili końca relacji ani zachowania pełnomocnictwa, które ujęto już w OBS-002-Q01."},
    {"id":"OBS-007-Q02","record_ids":["OBS-007-R02"],"understanding":"Obowiązek tajemnicy dotyczy kwalifikowanych informacji i trwa bez ograniczenia czasowego; reguły o byłym kliencie w art. 28-29 opisują natomiast odrębne przesłanki konfliktu.","variants":"Wariant A: OBSIL przechowuje status relacji klienta i ryzyko tajemnicy jako odrębne cechy; wariant B: status byłego klienta ma samodzielnie reprezentować oba zagadnienia; wariant C: tajemnica pozostaje osobnym obowiązkiem, lecz bez odrębnego znacznika systemowego.","consequences":"A ułatwia unikanie utożsamienia trwania tajemnicy z trwaniem relacji, lecz wymaga kryteriów danych o informacji; B może błędnie sugerować, że tajemnica zależy od statusu relacji; C zachowuje odrębność prawną bez dodatkowego pola.","question":"Czy w bazie pojęć i kontroli konfliktu tajemnicę dotyczącą informacji pozyskanych przy obsłudze należy oznaczać niezależnie od statusu aktualnego/byłego klienta, czy wystarczy odrębna instrukcja bez pola statusowego?","needed":"Decyzja ekspercka o modelu pojęciowym i ewentualnych polach, bez ponownego rozstrzygania daty końca relacji."}
  ],
  "self_check":"Przejrzano dziewięć źródeł w zakresach wskazanych w coverage, a historyczną kartę, OBS-002 i właściwe części tabeli konsultacji porównano pod kątem dublowania. Nie powtórzono KL-R04/07/08/09/10 ani OBS-002-R03–R07. Zapisano rozbieżność odesłania z SRC-01 jako kwestię redakcyjną do wyjaśnienia, a nie jako skorygowany cytat. Cytaty w evidence pobrano programowo z ciągłych wierszy luster. Q01 dotyczy mapowania norm, Q02 odrębności tajemnicy; nie powtórzono pytania OBS-002-Q01 o zakończenie relacji i pełnomocnictwo. Własne opracowanie częściowe, status OCZEKUJE i do odbioru Astry."
}

(HERE / "wynik.json").write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
