import json
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\adamj\Desktop\_KANCELARIA\OBSIL")
TASK_DIR = ROOT / "baza_wiedzy" / "kolejka_79" / "zadania" / "OBS-015" / "2811056334224caa8e3194d41df5b1ca"
job = json.loads((TASK_DIR / "zlecenie.json").read_text(encoding="utf-8"))
sources = {
    source["id"]: (ROOT / source["text"]).read_text(encoding="utf-8-sig").splitlines()
    for source in job["sources"]
}

def quote(source_id, start, end):
    return "\n".join(sources[source_id][start - 1:end])

result = {
    "task_id": "2811056334224caa8e3194d41df5b1ca",
    "concept_id": "OBS-015",
    "label": "interes klienta",
    "points": ["S2-K3-05", "S2-K3-08"],
    "scope": "Dla art. 28 ust. 1 i art. 29 ust. 1 pkt 1 uzupełniam rozumienie interesu klienta, nie powtarzając testu sprzeczności z OBS-057-R01, obowiązku lojalności z KL-R03 ani szczególnego oddzielenia interesu osoby prawnej, jej organów i grupy z OBS-069-R01. Art. 2 u.r.p. określa cel pomocy jako ochronę prawną interesów podmiotów, na rzecz których jest wykonywana. Autor poradnika wiąże ten cel z art. 8 KERP, a dla analizy konfliktu objaśnia lojalność jako działanie w interesie klienta dla osiągnięcia lub zachowania korzystnej dla niego sytuacji. KERP równocześnie ogranicza wykonywanie oczekiwań klienta przez niezależność i obowiązek przestrzegania prawa oraz etyki. Nie utożsamiam więc interesu klienta ani z samym życzeniem, ani z wyłącznie prawnym wynikiem. Jedno pytanie dotyczy wyłącznie treści i ustalania interesu pozaprawnego; nie powiela progu materialnej sprzeczności z OBS-057-Q01/G01 ani progu rozbieżność/sprzeczność obrony z OBS-030-Q01. Sprawdzono historyczną tabelę konsultacji i powiązane karty; nie ma w nich odrębnego rozstrzygnięcia tej kwestii. Zakres jest częściowy, bo korpus nie podaje metody ustalania lub dokumentowania pozaprawnego interesu klienta.",
    "completeness": "partial",
    "operator_status": "OCZEKUJE",
    "existing_record_refs": ["KL-R03", "SP-R04", "SP-R07", "OBS-057-R01", "OBS-069-R01"],
    "coverage": [
        {"source_id": "SRC-01", "status": "CZESCIOWY", "read_ranges": "928", "notes": "Komentarz w kontekście art. 28 ust. 1 opisuje interes przede wszystkim jako prawnie chroniony lub procesowy, dopuszcza też pozaprawny, np. ekonomiczny, i odsyła do rozumienia klienta. OBS-057-R01 zachowuje tę tezę; nie przepisuję jej jako nowego rekordu."},
        {"source_id": "SRC-02", "status": "CZESCIOWY", "read_ranges": "18-32; 70-76", "notes": "Wybrane relacje orzeczeń pokazują przeciwstawne interesy w konkretnych sytuacjach i rozróżnienie interesów prawnych. Są wtórnym wyborem i nie ustanawiają definicji interesu klienta."},
        {"source_id": "SRC-03", "status": "CZESCIOWY", "read_ranges": "340-365", "notes": "Poradnik autora łączy art. 2 u.r.p. i art. 8 KERP z lojalnością, a następnie objaśnia działanie dla osiągnięcia lub zachowania korzystnej sytuacji klienta. Dalsze wiersze 358-365 dotyczą art. 26 i wykorzystania wiedzy, nie są podstawą nowych rekordów. Ten sam autor co SRC-01."},
        {"source_id": "SRC-04", "status": "CZESCIOWY", "read_ranges": "63-75; 187-203", "notes": "Art. 6-9 KERP obejmuje rzetelność, niezależność, lojalność i dobro klienta; art. 7 ust. 2-3 wyznacza granicę wobec wpływów i oczekiwań sprzecznych z etyką lub obowiązkami. Art. 8 stanowi podstawę już odnotowaną w KL-R03; art. 28-29 potwierdza kontekst punktów."},
        {"source_id": "SRC-05", "status": "CZESCIOWY", "read_ranges": "25; 47; 93-99", "notes": "Art. 2 u.r.p. określa cel pomocy jako ochronę prawną interesów podmiotów, na których rzecz jest wykonywana; art. 4 i 6 dają kontekst świadczenia pomocy. Nie zawierają metody określania szczegółowej treści interesu klienta."},
        {"source_id": "SRC-06", "status": "CZESCIOWY", "read_ranges": "27-40; 117-137", "notes": "Wtórne zestawienie KERP wskazuje definicję klienta, funkcję lojalności i treść art. 28-29. Nie dostarcza odrębnej wykładni interesu klienta i nie jest niezależne od tekstu przepisów."},
        {"source_id": "SRC-07", "status": "CZESCIOWY", "read_ranges": "139-153; 161-171", "notes": "Wybrane wtórne opisy WO-17/24, WO-25/24, WO-42/24, WO-89/21 i WO-122/23 ilustrują konflikty oraz granice obowiązków; nie są ogólną definicją interesu klienta, a pełnych oryginałów tu brak."},
        {"source_id": "SRC-08", "status": "SPRAWDZONY", "read_ranges": "1-35", "notes": "Cały plik dotyczy tożsamości i związku spraw. Nie wnosi definicji interesu klienta."},
        {"source_id": "SRC-09", "status": "SPRAWDZONY", "read_ranges": "1-37", "notes": "Cały plik dotyczy klienta aktualnego i byłego oraz materialnego ustalenia odbiorcy pomocy. Nie definiuje treści interesu klienta."}
    ],
    "meanings": [
        {"id": "OBS-015-M01", "context": "Interes klienta w analizie sprzeczności między aktualnymi klientami, art. 28 ust. 1 i art. 29 ust. 1 pkt 1, punkty S2-K3-05 i S2-K3-08", "description": "Art. 2 u.r.p. określa ochronę prawną interesów podmiotu jako cel pomocy prawnej. W ujęciu autora lojalność oznacza działanie w interesie klienta dla osiągnięcia lub zachowania sytuacji dla niego korzystnej. Przy ustalaniu interesu nie wolno pomijać dopuszczonego w OBS-057-R01 interesu pozaprawnego, np. ekonomicznego, rozumianego w razie braku treści wyznaczonej prawem przez samego klienta. Pojęcie interesu pozostaje odrębne od pytania, czy interesy są materialnie sprzeczne. Oczekiwania klienta nie uchylają niezależności, prawa ani etyki zawodowej. Przy kliencie będącym osobą prawną nie utożsamia się automatycznie jego interesu z interesem organu lub grupy, zgodnie z OBS-069-R01.", "record_ids": ["OBS-015-R01", "OBS-015-R02", "OBS-015-R03", "KL-R03", "OBS-057-R01", "OBS-069-R01", "SP-R04", "SP-R07"]}
    ],
    "records": [
        {"id": "OBS-015-R01", "kind": "przepis", "claim": "Art. 2 u.r.p. ujmuje cel pomocy prawnej jako ochronę prawną interesów podmiotów, na rzecz których pomoc jest wykonywana.", "speaker": "Ustawa o radcach prawnych, art. 2 w lokalnym tekście SRC-05", "role": "tekst normatywny lokalnej kopii", "context": "Cel pomocy prawnej świadczonej przez radcę prawnego na rzecz danego podmiotu.", "court_treatment": "nie_dotyczy", "source_status": "lokalna kopia ustawy z manifestu; aktualności tekstu nie weryfikowano", "evidence": [{"source_id": "SRC-05", "line_start": 25, "line_end": 25, "quote": quote("SRC-05", 25, 25)}], "limits": "Przepis określa cel pomocy i krąg beneficjentów, ale nie wylicza rodzajów interesu ani nie definiuje szczegółowej treści interesu klienta. Nie przesądza, że przy analizie art. 28-29 uwzględnia się wyłącznie interes prawnie chroniony."},
        {"id": "OBS-015-R02", "kind": "poglad_autora", "claim": "Autor poradnika odczytuje art. 2 u.r.p. i art. 8 KERP jako ukierunkowujące pomoc na interes prawny klienta, jego dobro i ochronę praw. Dla analizy konfliktu objaśnia lojalność jako wykonywanie wszystkich czynności zawodowych w interesie klienta, aby osiągnąć lub zachować sytuację dla niego korzystną; materialna sprzeczność może w niektórych przypadkach przyjmować postać konfliktu lojalności wobec różnych klientów.", "speaker": "P. Skuczyński, autor poradnika SRC-03", "role": "autor opracowania poradnikowego", "context": "Fragment o lojalności wobec klienta i materialnej sprzeczności interesów. Pogląd rozwija, ale nie zastępuje definicji materialnej sprzeczności z OBS-057-R01.", "court_treatment": "nie_dotyczy; pogląd autora poradnika, nie stanowisko sądu", "source_status": "poradnik; SRC-01 i SRC-03 pochodzą od tego samego autora, nie są niezależnymi opiniami", "evidence": [{"source_id": "SRC-03", "line_start": 340, "line_end": 357, "quote": quote("SRC-03", 340, 357)}], "limits": "To objaśnienie zasady lojalności w kontekście konfliktu interesów, a nie autonomiczna definicja ustawowa każdego interesu klienta. Zwrot o sytuacji korzystnej nie podaje mierników jej ustalania i nie oznacza, że interes klienta pokrywa się z każdym jego oczekiwaniem. Autor zaznacza, że materialny konflikt lojalności może występować przynajmniej w niektórych przypadkach."},
        {"id": "OBS-015-R03", "kind": "przepis", "claim": "KERP łączy niezależność radcy z wolnością od wpływu jego interesów osobistych, nacisków zewnętrznych i ingerencji, a zarazem zakazuje naruszania etyki lub obowiązków zawodowych w celu spełnienia oczekiwań klienta albo osób trzecich.", "speaker": "Kodeks Etyki Radcy Prawnego, art. 7 ust. 2-3 w lokalnym tekście SRC-04", "role": "tekst normatywny lokalnej kopii", "context": "Granica dla rozumienia dobra i interesu klienta przy wykonywaniu czynności zawodowych.", "court_treatment": "nie_dotyczy", "source_status": "lokalna kopia KERP z manifestu; aktualności tekstu nie weryfikowano", "evidence": [{"source_id": "SRC-04", "line_start": 69, "line_end": 71, "quote": quote("SRC-04", 69, 71)}], "limits": "Przepis nie definiuje interesu klienta ani nie ustanawia samodzielnego testu sprzeczności. Ogranicza utożsamienie interesu z oczekiwaniem klienta, jeżeli jego realizacja naruszałaby niezależność, etykę lub obowiązki zawodowe."}
    ],
    "relations": [],
    "gaps": [
        {"id": "OBS-015-G01", "issue": "Źródła określają cel pomocy i dopuszczają uwzględnianie interesu pozaprawnego według rozumienia klienta, ale nie podają metody ustalania lub dokumentowania jego treści, zwłaszcza gdy klient nie wyraził jej jasno albo pozostaje w napięciu z jego interesem prawnym. Brak ten wiąże się z OBS-057-G01, lecz nie dotyczy progu, przy którym dwa ustalone interesy stają się sprzeczne.", "needed": "Wskazówki eksperta, jakie fakty i wypowiedzi klienta pozwalają ustalić jego pozaprawny interes oraz jak zachować rozróżnienie między interesem zadeklarowanym a oceną radcy."}
    ],
    "questions": [
        {"id": "OBS-015-Q01", "record_ids": ["OBS-015-R01", "OBS-015-R02", "OBS-015-R03", "OBS-057-R01", "OBS-069-R01", "KL-R03"], "understanding": "Art. 2 u.r.p. określa prawny cel pomocy, a komentarz opisuje interes klienta również jako sytuację korzystną, którą czynności mają osiągnąć lub zachować. OBS-057-R01 dopuszcza w kontekście materialnej sprzeczności interesy pozaprawne, w tym ekonomiczne, i odsyła do ich rozumienia przez klienta. KERP art. 7 ogranicza obowiązek realizacji oczekiwań klienta przez niezależność i etykę. Pytanie dotyczy ustalenia przedmiotu interesu, nie progu jego sprzeczności ani odrębnego standardu art. 30 lub obrony kilku oskarżonych.", "variants": "A: interes klienta dla art. 28 ust. 1 i art. 29 ust. 1 pkt 1 obejmuje wyłącznie interes prawnie chroniony lub procesowy; deklaracje pozaprawne mogą mieć znaczenie tylko o tyle, o ile przekładają się na te interesy. B: istotne mogą być także interesy pozaprawne, zwłaszcza ekonomiczne, a ich treść ustala się przez rozumienie i cele przedstawione przez klienta, z zachowaniem granic prawa, etyki i niezależności. C: kategorie prawna i pozaprawna należy ujmować łącznie, przy czym w razie ich rozbieżności radca powinien odrębnie zapisać interes prawny oraz cel klienta i nie zakładać, że jeden zastępuje drugi.", "consequences": "Wariant A zawęża ocenę konfliktu do interesów prawnie chronionych lub procesowych. Wariant B uwzględnia także ekonomiczne cele klienta, ale wymaga ustalenia ich treści bez domyślnego przypisywania. Wariant C zachowuje oba poziomy i ujawnia rozbieżności. Każdy wariant pozostawia oddzielne pytanie, czy interesy są nie do pogodzenia, oraz nie rozstrzyga progu znacznego ryzyka z art. 30.", "question": "Jak ustalać treść interesu klienta w art. 28 ust. 1 i art. 29 ust. 1 pkt 1, gdy chodzi o interes pozaprawny, zwłaszcza ekonomiczny? Czy należy uwzględnić cele rozumiane i przedstawione przez klienta obok jego interesu prawnego, a jeśli tak, jakie źródła informacji i sposób dokumentacji pozwalają je rzetelnie ustalić bez utożsamienia ich z każdym oczekiwaniem klienta?", "needed": "Wykładnia ekspercka relacji między art. 2 u.r.p., art. 7-8 KERP oraz komentarzowym ujęciem interesu klienta, ze wskazaniem sposobu ustalania interesu pozaprawnego. Osobno pozostają ocena materialnej sprzeczności z OBS-057 i jej przykłady w kontekście obrony z OBS-030."}
    ],
    "self_check": "Odczytano brief, zakres partii, index odebranych kart, PLAN_BUDOWY_BAZY oraz relewantne fragmenty wszystkich dziewięciu źródeł. Cytaty OBS-015-R01-R03 pobiera skrypt jako dokładne ciągi z manifestu: SRC-05 w. 25, SRC-03 w. 340-357 i SRC-04 w. 69-71. R01 dotyczy celu ochrony prawnej, R02 rozwija autorową formułę korzystnej sytuacji, a R03 zachowuje granicę niezależności i etyki; nie powielono KL-R03 ani OBS-057-R01. Pytanie dotyczy wyłącznie ustalania treści interesu pozaprawnego, nie progu sprzeczności z OBS-057-Q01 ani przykładów obrony z OBS-030-Q01. Operator status OCZEKUJE; odbiór pozostaje po stronie Astry."
}

out = TASK_DIR / "wynik.json"
out.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(out)

sys.path.insert(0, str(ROOT / "narzedzia" / "kolejka_pojec"))
import kolejka
state = kolejka.load(ROOT / "baza_wiedzy" / "kolejka_79")
task = kolejka.get_job(state, result["concept_id"])
kolejka.validate_result(state, task, result)
print("validate_result: OK (bez zapisu do kolejki)")
